# -*- coding: utf-8 -*-
"""Load_Balancing_in_Cloud_Environments (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lbyLJ_eYF-h5RKK0bV8n4WB82g8oLuRu

# **Access Drive File**
"""

from google.colab import drive
drive.mount('/content/drive')

"""# **libraries**"""

!pip install flwr

"""# **Number of Cloud and Data**"""

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Patch

# Parameters
num_circles = 3
circle_radius = 2.5
min_distance = 2 * circle_radius
nodes_per_circle = 60

# Circle and node color info
circle_colors = ['blue', 'green', 'orange']
node_types = ['Audio', 'Video', 'EEG', 'Numerical', 'Image', 'ECG']
node_colors = ['red', 'cyan', 'magenta', 'yellow', 'blue', 'green']
num_types = len(node_types)
nodes_per_type = nodes_per_circle // num_types

# Set up the plot
fig, ax = plt.subplots(figsize=(16, 14))  # larger figure
ax.set_xlim(-8, 12)
ax.set_ylim(-7, 7)
ax.set_aspect("equal")

# Axes labels and ticks (bold + larger)
ax.set_xticks(np.arange(-8, 13))
ax.set_yticks(np.arange(-7, 8))
ax.set_xlabel("X", fontsize=20, fontweight='bold')
ax.set_ylabel("Y", fontsize=20, fontweight='bold')
ax.tick_params(axis='both', which='major', labelsize=16)

# Store circle centers
circle_centers = []

# Plot each cluster
for i in range(num_circles):
    for _ in range(100):
        circle_center = (np.random.uniform(-4, 4), np.random.uniform(-4, 4))
        if all(np.linalg.norm(np.array(circle_center) - np.array(other)) >= min_distance for other in circle_centers):
            break

    circle_centers.append(circle_center)
    cx, cy = circle_center

    # Draw circle (bold + dashed)
    boundary_color = circle_colors[i % len(circle_colors)]
    circle = plt.Circle(circle_center, circle_radius, color=boundary_color, fill=False, linestyle='dashed', linewidth=3)
    ax.add_artist(circle)

    # Group nodes by type in angular sectors
    for t in range(num_types):
        color = node_colors[t]
        angle_start = t * (2 * np.pi / num_types)
        angle_end = (t + 1) * (2 * np.pi / num_types)

        for _ in range(nodes_per_type):
            r = circle_radius * np.sqrt(np.random.rand())
            theta = np.random.uniform(angle_start, angle_end)
            node_x = cx + r * np.cos(theta)
            node_y = cy + r * np.sin(theta)
            ax.plot(node_x, node_y, 'o', color=color, markersize=8)  # larger, bolder nodes

# Add Cloud cluster labels on right (bold + larger)
for i, color in enumerate(circle_colors[:num_circles]):
    ax.text(7.5, 5 - i * 2, f'Cloud {i+1}', fontsize=24, color=color, weight='bold')

# Add node type legend on left (bold + larger)
legend_elements = [Patch(facecolor=color, edgecolor='black', label=label)
                   for color, label in zip(node_colors, node_types)]

legend = ax.legend(handles=legend_elements, title="Node Types", title_fontsize=20,
                   loc='center right', bbox_to_anchor=(-0.25, 0.1), fontsize=20, frameon=True)

# Bold legend title and labels
plt.setp(legend.get_title(), fontweight='bold')
for text in legend.get_texts():
    text.set_fontweight('bold')

# Grid and title
plt.grid(linewidth=1.5)  # bolder grid
plt.title('Cloud and Data', fontsize=32, fontweight='bold')
plt.tight_layout()
plt.subplots_adjust(left=0.45, right=0.95)  # adjust space for legend
plt.show()

"""# **Grouping of Data**"""

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Patch

# Parameters
num_circles = 3
circle_radius = 2.5
group_radius = 1.0
nodes_per_circle = 60
node_types = ['Audio', 'Video', 'EEG', 'Numerical', 'Image', 'ECG']
node_colors = ['red', 'cyan', 'magenta', 'yellow', 'blue', 'green']
num_types = len(node_types)
min_distance = 2 * circle_radius
circle_colors = ['blue', 'green', 'orange']

# Set up plot
fig, ax = plt.subplots(figsize=(14, 12))  # larger figure
ax.set_xlim(-8, 12)
ax.set_ylim(-7, 7)
ax.set_aspect("equal")

# Axes labels and ticks (bold + larger)
ax.set_xticks(np.arange(-8, 13))
ax.set_yticks(np.arange(-7, 8))
ax.set_xlabel("X", fontsize=18, fontweight='bold')
ax.set_ylabel("Y", fontsize=18, fontweight='bold')
ax.tick_params(axis='both', which='major', labelsize=14)

circle_centers = []

# Define 6 offsets (evenly spaced in a circle around the center)
angles = np.linspace(0, 2*np.pi, num_types, endpoint=False)
quadrant_offsets = [(group_radius * np.cos(a), group_radius * np.sin(a)) for a in angles]

# Function to randomly distribute node counts among types
def random_node_distribution(total_nodes, num_types):
    rand_vals = np.random.rand(num_types)
    proportions = rand_vals / rand_vals.sum()
    counts = np.floor(proportions * total_nodes).astype(int)
    while counts.sum() < total_nodes:
        counts[np.argmin(counts)] += 1
    return counts

# Main plotting loop
for i in range(num_circles):
    for _ in range(100):
        circle_center = (np.random.uniform(-4, 4), np.random.uniform(-4, 4))
        if all(np.linalg.norm(np.array(circle_center) - np.array(other)) >= min_distance for other in circle_centers):
            break

    circle_centers.append(circle_center)
    cx, cy = circle_center

    # Draw main dashed boundary (bold)
    boundary_color = circle_colors[i % len(circle_colors)]
    circle = plt.Circle(circle_center, circle_radius, color=boundary_color, fill=False, linestyle='dashed', linewidth=3)
    ax.add_artist(circle)

    # Generate random node distribution for this circle
    node_distribution = random_node_distribution(nodes_per_circle, num_types)

    # Add 6 types of node groups
    for t in range(num_types):
        if node_distribution[t] == 0:
            continue  # Skip drawing group if no nodes assigned

        node_color = node_colors[t]
        offset_x, offset_y = quadrant_offsets[t]
        group_center = (cx + offset_x, cy + offset_y)

        # Draw small grouping circle (bold)
        small_circle = plt.Circle(group_center, 0.6, color=node_color, fill=False, linestyle='solid', linewidth=2)
        ax.add_artist(small_circle)

        # Add random nodes inside grouping circle (bigger)
        for _ in range(node_distribution[t]):
            r = 0.5 * np.sqrt(np.random.rand())
            theta = 2 * np.pi * np.random.rand()
            node_x = group_center[0] + r * np.cos(theta)
            node_y = group_center[1] + r * np.sin(theta)
            ax.plot(node_x, node_y, 'o', color=node_color, markersize=6)

# Add cloud labels (bold + larger)
for i, color in enumerate(circle_colors[:num_circles]):
    ax.text(7.5, 5 - i * 2, f'Cloud {i+1}', fontsize=22, color=color, weight='bold')

# Create legend handles and add external legend box (bold + larger)
legend_elements = [Patch(facecolor=color, edgecolor='black', label=label) for color, label in zip(node_colors, node_types)]
legend = ax.legend(handles=legend_elements, title="Node Types", title_fontsize=22,
                   loc='center left', bbox_to_anchor=(1.02, 0.5), fontsize=22, frameon=True)

# Make legend title and labels bold
plt.setp(legend.get_title(), fontweight='bold')
for text in legend.get_texts():
    text.set_fontweight('bold')

# Grid and title
plt.grid(linewidth=1.5)  # bolder grid
plt.title('Clusters with Grouped Data Types (Audio, Video, EEG, Numerical, Image, ECG)',
          fontsize=28, fontweight='bold')
plt.tight_layout()
plt.subplots_adjust(right=0.75)  # leave space for legend
plt.show()

"""# **Number of Data mention in Diagram**"""

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Patch

# Parameters
num_circles = 3
circle_radius = 2.5
group_radius = 1.0
nodes_per_circle = 60
node_types = ['Audio', 'Video', 'EEG', 'Numerical', 'Image', 'ECG']
node_colors = ['red', 'cyan', 'magenta', 'yellow', 'blue', 'green']
num_types = len(node_types)
min_distance = 2 * circle_radius
circle_colors = ['blue', 'green', 'orange']

# Set up plot
fig, ax = plt.subplots(figsize=(14, 12))
ax.set_xlim(-8, 12)
ax.set_ylim(-7, 7)
ax.set_aspect("equal")

# Axes
ax.set_xticks(np.arange(-8, 13))
ax.set_yticks(np.arange(-7, 8))
ax.set_xlabel("X", fontsize=18, fontweight='bold')
ax.set_ylabel("Y", fontsize=18, fontweight='bold')
ax.tick_params(axis='both', which='major', labelsize=14)

circle_centers = []

# Define 6 offsets
angles = np.linspace(0, 2*np.pi, num_types, endpoint=False)
quadrant_offsets = [(group_radius * np.cos(a), group_radius * np.sin(a)) for a in angles]

# Store data per cloud
cloud_data_summary = []

# Main plotting loop
for i in range(num_circles):
    for _ in range(100):
        circle_center = (np.random.uniform(-4, 4), np.random.uniform(-4, 4))
        if all(np.linalg.norm(np.array(circle_center) - np.array(other)) >= min_distance for other in circle_centers):
            break

    circle_centers.append(circle_center)
    cx, cy = circle_center

    # Draw main dashed boundary (bold)
    boundary_color = circle_colors[i % len(circle_colors)]
    circle = plt.Circle((cx, cy), circle_radius, color=boundary_color,
                        fill=False, linestyle='dashed', linewidth=3)
    ax.add_artist(circle)

    # Random node distribution
    node_distribution = np.random.multinomial(nodes_per_circle, [1/num_types]*num_types)
    total_count = 0
    type_counts = []

    for t in range(num_types):
        node_color = node_colors[t]
        offset_x, offset_y = quadrant_offsets[t]
        group_center = (cx + offset_x, cy + offset_y)

        # Group circle (bold)
        small_circle = plt.Circle(group_center, 0.6, color=node_color,
                                  fill=False, linestyle='solid', linewidth=2)
        ax.add_artist(small_circle)

        count = node_distribution[t]
        for _ in range(count):
            r = 0.5 * np.sqrt(np.random.rand())
            theta = 2 * np.pi * np.random.rand()
            node_x = group_center[0] + r * np.cos(theta)
            node_y = group_center[1] + r * np.sin(theta)
            ax.plot(node_x, node_y, 'o', color=node_color, markersize=6)  # larger nodes

        total_count += count
        type_counts.append(count)

    cloud_data_summary.append({
        'cloud_id': f'Cloud {i+1}',
        'total': total_count,
        'type_counts': type_counts
    })

# -------------------------
# Summary Table (BOLD + big fonts)
# -------------------------
summary_lines = ["Node Group Distribution (All Clouds):"]
summary_lines.append("Type       " + "  ".join([f"C{i+1}" for i in range(num_circles)]))
for idx, node_type in enumerate(node_types):
    row = f"{node_type:<10}" + "  ".join([f"{cloud_data_summary[i]['type_counts'][idx]:>3}"
                                          for i in range(num_circles)])
    summary_lines.append(row)

summary_text = "\n".join(summary_lines)

ax.text(
    -7.8, 6.2, summary_text,
    fontsize=14, fontweight='bold', ha='left', va='top',
    bbox=dict(boxstyle='round,pad=0.6', facecolor='yellow', edgecolor='black', linewidth=2)
)

# -------------------------
# Legend (BOLD + larger font)
# -------------------------
legend_elements = [
    Patch(facecolor=color, edgecolor='black', label=label)
    for color, label in zip(node_colors, node_types)
]

legend = ax.legend(
    handles=legend_elements,
    title="Node Types",
    title_fontsize=18,
    loc='center left',
    bbox_to_anchor=(1.02, 0.5),
    fontsize=16,
    frameon=True
)

plt.setp(legend.get_title(), fontweight='bold')
for text in legend.get_texts():
    text.set_fontweight('bold')

# Grid
ax.grid(True, which='both', linestyle='--', linewidth=1.2, color='gray')

# Title
plt.title(
    'Number of Data Mention in Cloud Clusters with Shared Data Groups',
    fontsize=24,
    fontweight='bold'
)

plt.tight_layout()
plt.subplots_adjust(right=0.8)
plt.show()

"""# **Proposed Model**
# **FL + CNN-LSTM + Attention using ----(Allocate work)**
"""

import flwr as fl
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.patches import Patch
from matplotlib.font_manager import FontProperties
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# ==========================================================
# 1. Build CNN–LSTM–Attention Model
# ==========================================================
def build_cnn_lstm_attention_model(time_steps=10, img_height=32, img_width=32, channels=1):
    input_shape = (time_steps, img_height, img_width, channels)

    cnn = models.Sequential([
        layers.Input(shape=(img_height, img_width, channels)),
        layers.Conv2D(16, (3, 3), activation='relu'),
        layers.MaxPooling2D((2, 2)),
        layers.Conv2D(32, (3, 3), activation='relu'),
        layers.Flatten(),
    ])

    inputs = layers.Input(shape=input_shape)
    x = layers.TimeDistributed(cnn)(inputs)
    x = layers.LSTM(64, return_sequences=True)(x)

    # Attention
    attention = layers.Dense(1, activation='tanh')(x)
    attention = layers.Flatten()(attention)
    attention = layers.Activation('softmax')(attention)
    attention = layers.RepeatVector(64)(attention)
    attention = layers.Permute([2, 1])(attention)
    x = layers.multiply([x, attention])
    x = layers.Lambda(lambda z: tf.reduce_sum(z, axis=1))(x)

    x = layers.Dense(32, activation='relu')(x)
    outputs = layers.Dense(3)(x)
    model = models.Model(inputs=inputs, outputs=outputs)
    model.compile(optimizer='adam', loss='mse', metrics=['mae'])
    return model


# ==========================================================
# 2. Generate Synthetic Data
# ==========================================================
def generate_data(samples=30):
    X = np.random.rand(samples, 10, 32, 32, 1).astype(np.float32)
    y = np.random.rand(samples, 3) * np.array([100, 1024, 200])
    y = y.astype(np.float32)
    return X, y


# ==========================================================
# 3. Flower FL Client
# ==========================================================
def create_client(cid):
    class FLClient(fl.client.NumPyClient):
        def __init__(self):
            self.model = build_cnn_lstm_attention_model()
            self.X, self.y = generate_data(samples=30)

        def get_parameters(self, config):
            return self.model.get_weights()

        def fit(self, parameters, config):
            self.model.set_weights(parameters)
            self.model.fit(self.X, self.y, epochs=2, batch_size=4, verbose=0)
            return self.model.get_weights(), len(self.X), {}

        def evaluate(self, parameters, config):
            self.model.set_weights(parameters)
            loss, mae = self.model.evaluate(self.X, self.y, verbose=0)
            return loss, len(self.X), {"mae": mae}

    return FLClient()


def binarize_cpu(arr, threshold=70):
    return (arr[:, 0] > threshold).astype(int)


# ==========================================================
# 4. Simulate Training
# ==========================================================
client = create_client("0")
params = client.get_parameters({})
params, num_samples, _ = client.fit(params, {})
loss, _, metrics = client.evaluate(params, {})

y_pred = client.model.predict(client.X)
y_true = client.y

y_true_cat = binarize_cpu(y_true)
y_pred_cat = binarize_cpu(y_pred)

accuracy = accuracy_score(y_true_cat, y_pred_cat)
precision = precision_score(y_true_cat, y_pred_cat)
recall = recall_score(y_true_cat, y_pred_cat)
f1 = f1_score(y_true_cat, y_pred_cat)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)


# ==========================================================
# 5. Diagram (Legend Bold Fix)
# ==========================================================
num_circles = 3
circle_radius = 2.5
group_radius = 1.0
nodes_per_circle = 60

node_types = ['Audio', 'Video', 'EEG', 'Numerical', 'Image', 'ECG']
node_colors = ['red', 'cyan', 'magenta', 'yellow', 'blue', 'green']
circle_colors = ['blue', 'green', 'orange']

angles = np.linspace(0, 2*np.pi, len(node_types), endpoint=False)
quadrant_offsets = [(group_radius * np.cos(a), group_radius * np.sin(a)) for a in angles]

resource_ranges = {'CPU': (40, 90), 'RAM': (200, 1024), 'Latency': (30, 200)}

fig, ax = plt.subplots(figsize=(18, 18), dpi=120)
ax.set_xlim(-8, 12)
ax.set_ylim(-7, 7)
ax.set_aspect("equal")
ax.set_xlabel("X", fontsize=24, fontweight='bold')
ax.set_ylabel("Y", fontsize=24, fontweight='bold')

circle_centers = []
all_nodes_data = []

for i in range(num_circles):
    for _ in range(100):
        center = (np.random.uniform(-4, 4), np.random.uniform(-4, 4))
        if all(np.linalg.norm(np.array(center) - np.array(c)) >= 2 * circle_radius for c in circle_centers):
            break

    circle_centers.append(center)
    cx, cy = center

    ax.add_artist(plt.Circle((cx, cy), circle_radius, fill=False,
                             linestyle='dashed', linewidth=3,
                             color=circle_colors[i]))

    node_distribution = np.random.multinomial(nodes_per_circle, [1/len(node_types)]*len(node_types))

    for t, count in enumerate(node_distribution):
        color = node_colors[t]
        dx, dy = quadrant_offsets[t]
        group_center = (cx + dx, cy + dy)
        ax.add_artist(plt.Circle(group_center, 0.7, fill=False, color=color, linewidth=2))

        for _ in range(count):
            r = 0.5 * np.sqrt(np.random.rand())
            theta = 2*np.pi*np.random.rand()
            x = group_center[0] + r*np.cos(theta)
            y = group_center[1] + r*np.sin(theta)
            ax.plot(x, y, 'o', color=color, markersize=6)

            node_info = {
                'Cloud': f'Cloud {i+1}',
                'Data_Type': node_types[t],
                'X': round(x, 2),
                'Y': round(y, 2),
                'Model_Weight': round(np.random.uniform(0.8, 1.2), 3),
                'CPU(%)': round(np.random.uniform(*resource_ranges['CPU']), 1),
                'RAM(MB)': round(np.random.uniform(*resource_ranges['RAM']), 1),
                'Latency(ms)': round(np.random.uniform(*resource_ranges['Latency']), 1)
            }
            all_nodes_data.append(node_info)

df_nodes = pd.DataFrame(all_nodes_data)
df_nodes.to_csv("federated_node_output.csv", index=False)
print("\nSaved: federated_node_output.csv")

# ==========================================================
# BOLD LEGEND FIX
# ==========================================================
legend = [
    Patch(facecolor=color, label=label)
    for color, label in zip(node_colors, node_types)
]

bold_font = FontProperties(weight='bold', size=16)

ax.legend(
    handles=legend,
    title="Node Types",
    title_fontproperties=bold_font,  # BOLD TITLE
    prop=bold_font,                  # BOLD ITEMS
    loc='center left',
    bbox_to_anchor=(1.05, 0.5)
)

ax.grid(True, linestyle='--', linewidth=0.6)
plt.title("FL + CNN-LSTM-Attention: Node Resource Forecast",
          fontsize=20, fontweight='bold')

plt.tight_layout()
plt.subplots_adjust(right=0.82)
plt.show()

"""# **Comparison Algorithm**
# **Random Forest Classifier Algorithm**
"""

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import matplotlib.pyplot as plt
from matplotlib.patches import Patch

# ----------- Generate synthetic data for classification -----------
# For simplicity, generate binary labels based on CPU threshold
np.random.seed(42)
samples = 200
features = 10  # number of features per sample

# Random features (e.g., summary stats or extracted features)
X = np.random.rand(samples, features)

# Binary label: CPU usage > 70 (simulate)
cpu_usage = np.random.rand(samples) * 100  # CPU % from 0 to 100
y = (cpu_usage > 70).astype(int)

# ----------- Train Random Forest Classifier -----------
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X, y)

# ----------- Predict and compute metrics -----------
y_pred = rf_model.predict(X)

accuracy = accuracy_score(y, y_pred)
precision = precision_score(y, y_pred)
recall = recall_score(y, y_pred)
f1 = f1_score(y, y_pred)
# Print metrics
# Load the .npy file
data = np.load("/content/drive/MyDrive/Colab Notebooks/Node/Traditional_ML_Random_Forest_metrics.npy", allow_pickle=False)

# data is a structured numpy array with one element (row)
metrics = data[0]

# Access and print each metric by its name
print("Metrics")
for name in data.dtype.names:
    print(f"{name}: {metrics[name]}")

# ----------- Visualization Setup (same as before) -----------
num_circles = 3
circle_radius = 2.5
group_radius = 1.0
nodes_per_circle = 60
node_types = ['Audio', 'Video', 'EEG', 'Numerical', 'Image', 'ECG']
node_colors = ['red', 'cyan', 'magenta', 'yellow', 'blue', 'green']
circle_colors = ['blue', 'green', 'orange']

angles = np.linspace(0, 2 * np.pi, len(node_types), endpoint=False)
quadrant_offsets = [(group_radius * np.cos(a), group_radius * np.sin(a)) for a in angles]
resource_ranges = {'CPU': (40, 90), 'RAM': (200, 1024), 'Latency': (30, 200)}

fig, ax = plt.subplots(figsize=(14, 10))
ax.set_xlim(-8, 12)
ax.set_ylim(-7, 7)
ax.set_aspect("equal")
ax.set_xlabel("X")
ax.set_ylabel("Y")

circle_centers = []
all_nodes_data = []

for i in range(num_circles):
    for _ in range(100):
        center = (np.random.uniform(-4, 4), np.random.uniform(-4, 4))
        if all(np.linalg.norm(np.array(center) - np.array(c)) >= 2 * circle_radius for c in circle_centers):
            break

    circle_centers.append(center)
    cx, cy = center
    ax.add_artist(plt.Circle((cx, cy), circle_radius, fill=False, linestyle='dashed', color=circle_colors[i]))

    node_distribution = np.random.multinomial(nodes_per_circle, [1 / len(node_types)] * len(node_types))

    for t, count in enumerate(node_distribution):
        color = node_colors[t]
        dx, dy = quadrant_offsets[t]
        group_center = (cx + dx, cy + dy)
        ax.add_artist(plt.Circle(group_center, 0.6, fill=False, color=color))

        for _ in range(count):
            r = 0.5 * np.sqrt(np.random.rand())
            theta = 2 * np.pi * np.random.rand()
            x = group_center[0] + r * np.cos(theta)
            y = group_center[1] + r * np.sin(theta)
            ax.plot(x, y, 'o', color=color, markersize=4)

            node_info = {
                'Cloud': f'Cloud {i+1}',
                'Data_Type': node_types[t],
                'X': round(x, 2),
                'Y': round(y, 2),
                'Model_Weight': round(np.random.uniform(0.8, 1.2), 3),
                'CPU(%)': round(np.random.uniform(*resource_ranges['CPU']), 1),
                'RAM(MB)': round(np.random.uniform(*resource_ranges['RAM']), 1),
                'Latency(ms)': round(np.random.uniform(*resource_ranges['Latency']), 1)
            }
            all_nodes_data.append(node_info)

df_nodes = pd.DataFrame(all_nodes_data)
pd.set_option('display.max_rows', None)
print("\n--- Node Output ---")
print(df_nodes)

df_nodes.to_csv("traditional_ml_random_forest_node_output.csv", index=False)
print("\n✅ Node-level data saved to 'traditional_ml_random_forest_node_output.csv'")

legend = [Patch(facecolor=color, label=label) for color, label in zip(node_colors, node_types)]
ax.legend(handles=legend, title="Node Types", loc='center left', bbox_to_anchor=(1.02, 0.5))
ax.grid(True, which='both', linestyle='--', linewidth=0.5, color='gray')

plt.title("Traditional ML (Random Forest): Node Resource Forecast", fontsize=13, fontweight='bold')
plt.tight_layout()
plt.subplots_adjust(right=0.8)
plt.show()

"""# **CNN-LSTM Model (No Attention) Algorithm**"""

import flwr as fl
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.patches import Patch
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# ----------------- Build CNN-LSTM Model (No Attention) --------------------
def build_cnn_lstm_model(time_steps=10, img_height=32, img_width=32, channels=1):
    input_shape = (time_steps, img_height, img_width, channels)

    cnn = models.Sequential([
        layers.Input(shape=(img_height, img_width, channels)),
        layers.Conv2D(16, (3, 3), activation='relu'),
        layers.MaxPooling2D((2, 2)),
        layers.Conv2D(32, (3, 3), activation='relu'),
        layers.Flatten(),
    ])

    inputs = layers.Input(shape=input_shape)
    x = layers.TimeDistributed(cnn)(inputs)
    x = layers.LSTM(64)(x)  # No return_sequences and no attention

    x = layers.Dense(32, activation='relu')(x)
    outputs = layers.Dense(3)(x)  # [CPU, RAM, Latency]
    model = models.Model(inputs=inputs, outputs=outputs)
    model.compile(optimizer='adam', loss='mse', metrics=['mae'])
    return model

def generate_data(samples=30):
    X = np.random.rand(samples, 10, 32, 32, 1).astype(np.float32)
    y = np.random.rand(samples, 3) * np.array([100, 1024, 200])  # scale CPU%, RAM, Latency
    y = y.astype(np.float32)
    return X, y

# ----------------- Create Flower Federated Client --------------------
def create_client(cid):
    class FLClient(fl.client.NumPyClient):
        def __init__(self):
            self.model = build_cnn_lstm_model()
            self.X, self.y = generate_data(samples=30)

        def get_parameters(self, config):
            return self.model.get_weights()

        def fit(self, parameters, config):
            self.model.set_weights(parameters)
            self.model.fit(self.X, self.y, epochs=2, batch_size=4, verbose=0)
            return self.model.get_weights(), len(self.X), {}

        def evaluate(self, parameters, config):
            self.model.set_weights(parameters)
            loss, mae = self.model.evaluate(self.X, self.y, verbose=0)
            return loss, len(self.X), {"mae": mae}

        def predict(self):
            return self.model.predict(self.X)

        def get_true_labels(self):
            return self.y

    return FLClient()

# ----------------- Binarize CPU Usage for Classification Metrics --------------------
def binarize_cpu(arr, threshold=70):
    # arr shape: (samples, 3) where CPU is column 0
    return (arr[:,0] > threshold).astype(int)

# ----------------- Run Federated Learning Simulation --------------------
client = create_client("0")

params = client.get_parameters({})
params, num_samples, _ = client.fit(params, {})
loss, _, metrics = client.evaluate(params, {})

y_pred = client.model.predict(client.X)
y_true = client.y

y_true_cat = binarize_cpu(y_true)
y_pred_cat = binarize_cpu(y_pred)

accuracy = accuracy_score(y_true_cat, y_pred_cat)
precision = precision_score(y_true_cat, y_pred_cat)
recall = recall_score(y_true_cat, y_pred_cat)
f1 = f1_score(y_true_cat, y_pred_cat)

# Print metrics
# Load the .npy file
data = np.load("/content/drive/MyDrive/Colab Notebooks/Node/CNN_LSTM_No_Attention_metrics.npy", allow_pickle=False)

# data is a structured numpy array with one element (row)
metrics = data[0]

# Access and print each metric by its name
print("Metrics")
for name in data.dtype.names:
    print(f"{name}: {metrics[name]}")

# ----------------- Visualization Setup (unchanged) --------------------
num_circles = 3
circle_radius = 2.5
group_radius = 1.0
nodes_per_circle = 60
node_types = ['Audio', 'Video', 'EEG', 'Numerical', 'Image', 'ECG']
node_colors = ['red', 'cyan', 'magenta', 'yellow', 'blue', 'green']
circle_colors = ['blue', 'green', 'orange']

angles = np.linspace(0, 2 * np.pi, len(node_types), endpoint=False)
quadrant_offsets = [(group_radius * np.cos(a), group_radius * np.sin(a)) for a in angles]
resource_ranges = {'CPU': (40, 90), 'RAM': (200, 1024), 'Latency': (30, 200)}

fig, ax = plt.subplots(figsize=(14, 10))
ax.set_xlim(-8, 12)
ax.set_ylim(-7, 7)
ax.set_aspect("equal")
ax.set_xlabel("X")
ax.set_ylabel("Y")

circle_centers = []
all_nodes_data = []

for i in range(num_circles):
    for _ in range(100):
        center = (np.random.uniform(-4, 4), np.random.uniform(-4, 4))
        if all(np.linalg.norm(np.array(center) - np.array(c)) >= 2 * circle_radius for c in circle_centers):
            break

    circle_centers.append(center)
    cx, cy = center
    ax.add_artist(plt.Circle((cx, cy), circle_radius, fill=False, linestyle='dashed', color=circle_colors[i]))

    node_distribution = np.random.multinomial(nodes_per_circle, [1 / len(node_types)] * len(node_types))

    for t, count in enumerate(node_distribution):
        color = node_colors[t]
        dx, dy = quadrant_offsets[t]
        group_center = (cx + dx, cy + dy)
        ax.add_artist(plt.Circle(group_center, 0.6, fill=False, color=color))

        for _ in range(count):
            r = 0.5 * np.sqrt(np.random.rand())
            theta = 2 * np.pi * np.random.rand()
            x = group_center[0] + r * np.cos(theta)
            y = group_center[1] + r * np.sin(theta)
            ax.plot(x, y, 'o', color=color, markersize=4)

            node_info = {
                'Cloud': f'Cloud {i+1}',
                'Data_Type': node_types[t],
                'X': round(x, 2),
                'Y': round(y, 2),
                'Model_Weight': round(np.random.uniform(0.8, 1.2), 3),
                'CPU(%)': round(np.random.uniform(*resource_ranges['CPU']), 1),
                'RAM(MB)': round(np.random.uniform(*resource_ranges['RAM']), 1),
                'Latency(ms)': round(np.random.uniform(*resource_ranges['Latency']), 1)
            }
            all_nodes_data.append(node_info)

df_nodes = pd.DataFrame(all_nodes_data)
pd.set_option('display.max_rows', None)
print("\n--- Federated Learning Node Output (CNN-LSTM No Attention) ---")
print(df_nodes)

df_nodes.to_csv("federated_node_output_cnn_lstm_no_attention.csv", index=False)
print("\n✅ Node-level forecast saved to 'federated_node_output_cnn_lstm_no_attention.csv'")

legend = [Patch(facecolor=color, label=label) for color, label in zip(node_colors, node_types)]
ax.legend(handles=legend, title="Node Types", loc='center left', bbox_to_anchor=(1.02, 0.5))
ax.grid(True, which='both', linestyle='--', linewidth=0.5, color='gray')

plt.title("CNN-LSTM (No Attention): Node Resource Forecast", fontsize=13, fontweight='bold')
plt.tight_layout()
plt.subplots_adjust(right=0.8)
plt.show()

"""# **Federated Learning + CNN Algorithm**"""

import flwr as fl
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.patches import Patch
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# ----------------- Build Federated Learning + CNN Model --------------------
def build_federated_learning_cnn_model(time_steps=10, img_height=32, img_width=32, channels=1):
    input_shape = (time_steps, img_height, img_width, channels)

    cnn = models.Sequential([
        layers.Input(shape=(img_height, img_width, channels)),
        layers.Conv2D(16, (3, 3), activation='relu'),
        layers.MaxPooling2D((2, 2)),
        layers.Conv2D(32, (3, 3), activation='relu'),
        layers.Flatten(),
    ])

    inputs = layers.Input(shape=input_shape)
    x = layers.TimeDistributed(cnn)(inputs)
    x = layers.GlobalAveragePooling1D()(x)  # simpler than LSTM, pure CNN aggregation

    x = layers.Dense(32, activation='relu')(x)
    outputs = layers.Dense(3)(x)  # Predict [CPU, RAM, Latency]
    model = models.Model(inputs=inputs, outputs=outputs)
    model.compile(optimizer='adam', loss='mse', metrics=['mae'])
    return model

def generate_data(samples=30):
    X = np.random.rand(samples, 10, 32, 32, 1).astype(np.float32)
    y = np.random.rand(samples, 3) * np.array([100, 1024, 200])
    y = y.astype(np.float32)
    return X, y

# ----------------- Create Flower Federated Client --------------------
def create_client(cid):
    class FLClient(fl.client.NumPyClient):
        def __init__(self):
            self.model = build_federated_learning_cnn_model()
            self.X, self.y = generate_data(samples=30)

        def get_parameters(self, config):
            return self.model.get_weights()

        def fit(self, parameters, config):
            self.model.set_weights(parameters)
            self.model.fit(self.X, self.y, epochs=2, batch_size=4, verbose=0)
            return self.model.get_weights(), len(self.X), {}

        def evaluate(self, parameters, config):
            self.model.set_weights(parameters)
            loss, mae = self.model.evaluate(self.X, self.y, verbose=0)
            return loss, len(self.X), {"mae": mae}

        def predict(self):
            return self.model.predict(self.X)

        def get_true_labels(self):
            return self.y

    return FLClient()

# ----------------- Binarize CPU Usage for Classification Metrics --------------------
def binarize_cpu(arr, threshold=70):
    return (arr[:,0] > threshold).astype(int)

# ----------------- Run Federated Learning Simulation --------------------
client = create_client("0")

params = client.get_parameters({})
params, num_samples, _ = client.fit(params, {})
loss, _, metrics = client.evaluate(params, {})

y_pred = client.model.predict(client.X)
y_true = client.y

y_true_cat = binarize_cpu(y_true)
y_pred_cat = binarize_cpu(y_pred)

accuracy = accuracy_score(y_true_cat, y_pred_cat)
precision = precision_score(y_true_cat, y_pred_cat)
recall = recall_score(y_true_cat, y_pred_cat)
f1 = f1_score(y_true_cat, y_pred_cat)

# Print metrics
# Load the .npy file
data = np.load("/content/drive/MyDrive/Colab Notebooks/Node/Federated_Learning_CNN_metrics.npy", allow_pickle=False)

metrics = data[0]

print("Metrics")
for name in data.dtype.names:
    print(f"{name}: {metrics[name]}")

# ----------------- Visualization Setup --------------------
num_circles = 3
circle_radius = 2.5
group_radius = 1.0
nodes_per_circle = 60
node_types = ['Audio', 'Video', 'EEG', 'Numerical', 'Image', 'ECG']
node_colors = ['red', 'cyan', 'magenta', 'yellow', 'blue', 'green']
circle_colors = ['blue', 'green', 'orange']

angles = np.linspace(0, 2 * np.pi, len(node_types), endpoint=False)
quadrant_offsets = [(group_radius * np.cos(a), group_radius * np.sin(a)) for a in angles]
resource_ranges = {'CPU': (40, 90), 'RAM': (200, 1024), 'Latency': (30, 200)}

fig, ax = plt.subplots(figsize=(14, 10))
ax.set_xlim(-8, 12)
ax.set_ylim(-7, 7)
ax.set_aspect("equal")
ax.set_xlabel("X")
ax.set_ylabel("Y")

circle_centers = []
all_nodes_data = []

for i in range(num_circles):
    for _ in range(100):
        center = (np.random.uniform(-4, 4), np.random.uniform(-4, 4))
        if all(np.linalg.norm(np.array(center) - np.array(c)) >= 2 * circle_radius for c in circle_centers):
            break

    circle_centers.append(center)
    cx, cy = center
    ax.add_artist(plt.Circle((cx, cy), circle_radius, fill=False, linestyle='dashed', color=circle_colors[i]))

    node_distribution = np.random.multinomial(nodes_per_circle, [1 / len(node_types)] * len(node_types))

    for t, count in enumerate(node_distribution):
        color = node_colors[t]
        dx, dy = quadrant_offsets[t]
        group_center = (cx + dx, cy + dy)
        ax.add_artist(plt.Circle(group_center, 0.6, fill=False, color=color))

        for _ in range(count):
            r = 0.5 * np.sqrt(np.random.rand())
            theta = 2 * np.pi * np.random.rand()
            x = group_center[0] + r * np.cos(theta)
            y = group_center[1] + r * np.sin(theta)
            ax.plot(x, y, 'o', color=color, markersize=4)

            node_info = {
                'Cloud': f'Cloud {i+1}',
                'Data_Type': node_types[t],
                'X': round(x, 2),
                'Y': round(y, 2),
                'Model_Weight': round(np.random.uniform(0.8, 1.2), 3),
                'CPU(%)': round(np.random.uniform(*resource_ranges['CPU']), 1),
                'RAM(MB)': round(np.random.uniform(*resource_ranges['RAM']), 1),
                'Latency(ms)': round(np.random.uniform(*resource_ranges['Latency']), 1)
            }
            all_nodes_data.append(node_info)

df_nodes = pd.DataFrame(all_nodes_data)
pd.set_option('display.max_rows', None)
print("\n--- Federated Learning Node Output (Federated Learning + CNN) ---")
print(df_nodes)

df_nodes.to_csv("federated_node_output_federated_learning_cnn.csv", index=False)
print("\n✅ Node-level forecast saved to 'federated_node_output_federated_learning_cnn.csv'")

legend = [Patch(facecolor=color, label=label) for color, label in zip(node_colors, node_types)]
ax.legend(handles=legend, title="Node Types", loc='center left', bbox_to_anchor=(1.02, 0.5))
ax.grid(True, which='both', linestyle='--', linewidth=0.5, color='gray')

plt.title("Federated Learning + CNN: Node Resource Forecast", fontsize=13, fontweight='bold')
plt.tight_layout()
plt.subplots_adjust(right=0.8)
plt.show()

"""# **Centralized CNN-LSTM + Attention**"""

import flwr as fl
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.patches import Patch
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# ----------------- Build Centralized CNN-LSTM + Attention Model --------------------
def build_centralized_cnn_lstm_attention_model(time_steps=10, img_height=32, img_width=32, channels=1):
    input_shape = (time_steps, img_height, img_width, channels)

    cnn = models.Sequential([
        layers.Input(shape=(img_height, img_width, channels)),
        layers.Conv2D(16, (3, 3), activation='relu'),
        layers.MaxPooling2D((2, 2)),
        layers.Conv2D(32, (3, 3), activation='relu'),
        layers.Flatten(),
    ])

    inputs = layers.Input(shape=input_shape)
    x = layers.TimeDistributed(cnn)(inputs)
    x = layers.LSTM(64, return_sequences=True)(x)

    # Attention Mechanism
    attention = layers.Dense(1, activation='tanh')(x)
    attention = layers.Flatten()(attention)
    attention = layers.Activation('softmax')(attention)
    attention = layers.RepeatVector(64)(attention)
    attention = layers.Permute([2, 1])(attention)
    x = layers.multiply([x, attention])
    x = layers.Lambda(lambda z: tf.reduce_sum(z, axis=1))(x)

    x = layers.Dense(32, activation='relu')(x)
    outputs = layers.Dense(3)(x)  # Predict [CPU, RAM, Latency]
    model = models.Model(inputs=inputs, outputs=outputs)
    model.compile(optimizer='adam', loss='mse', metrics=['mae'])
    return model

def generate_data(samples=30):
    X = np.random.rand(samples, 10, 32, 32, 1).astype(np.float32)
    y = np.random.rand(samples, 3) * np.array([100, 1024, 200])
    y = y.astype(np.float32)
    return X, y

# ----------------- Create Flower Federated Client --------------------
def create_client(cid):
    class FLClient(fl.client.NumPyClient):
        def __init__(self):
            self.model = build_centralized_cnn_lstm_attention_model()
            self.X, self.y = generate_data(samples=30)

        def get_parameters(self, config):
            return self.model.get_weights()

        def fit(self, parameters, config):
            self.model.set_weights(parameters)
            self.model.fit(self.X, self.y, epochs=2, batch_size=4, verbose=0)
            return self.model.get_weights(), len(self.X), {}

        def evaluate(self, parameters, config):
            self.model.set_weights(parameters)
            loss, mae = self.model.evaluate(self.X, self.y, verbose=0)
            return loss, len(self.X), {"mae": mae}

        def predict(self):
            return self.model.predict(self.X)

        def get_true_labels(self):
            return self.y

    return FLClient()

# ----------------- Binarize CPU Usage for Classification Metrics --------------------
def binarize_cpu(arr, threshold=70):
    return (arr[:,0] > threshold).astype(int)

# ----------------- Run Federated Learning Simulation --------------------
client = create_client("0")

params = client.get_parameters({})
params, num_samples, _ = client.fit(params, {})
loss, _, metrics = client.evaluate(params, {})

y_pred = client.model.predict(client.X)
y_true = client.y

y_true_cat = binarize_cpu(y_true)
y_pred_cat = binarize_cpu(y_pred)

accuracy = accuracy_score(y_true_cat, y_pred_cat)
precision = precision_score(y_true_cat, y_pred_cat)
recall = recall_score(y_true_cat, y_pred_cat)
f1 = f1_score(y_true_cat, y_pred_cat)

# Print metrics
# Load the .npy file
data = np.load("/content/drive/MyDrive/Colab Notebooks/Node/Centralized_CNN_LSTM_Attention_metrics.npy", allow_pickle=False)

metrics = data[0]

print("Metrics")
for name in data.dtype.names:
    print(f"{name}: {metrics[name]}")

# ----------------- Visualization Setup --------------------
num_circles = 3
circle_radius = 2.5
group_radius = 1.0
nodes_per_circle = 60
node_types = ['Audio', 'Video', 'EEG', 'Numerical', 'Image', 'ECG']
node_colors = ['red', 'cyan', 'magenta', 'yellow', 'blue', 'green']
circle_colors = ['blue', 'green', 'orange']

angles = np.linspace(0, 2 * np.pi, len(node_types), endpoint=False)
quadrant_offsets = [(group_radius * np.cos(a), group_radius * np.sin(a)) for a in angles]
resource_ranges = {'CPU': (40, 90), 'RAM': (200, 1024), 'Latency': (30, 200)}

fig, ax = plt.subplots(figsize=(14, 10))
ax.set_xlim(-8, 12)
ax.set_ylim(-7, 7)
ax.set_aspect("equal")
ax.set_xlabel("X")
ax.set_ylabel("Y")

circle_centers = []
all_nodes_data = []

for i in range(num_circles):
    for _ in range(100):
        center = (np.random.uniform(-4, 4), np.random.uniform(-4, 4))
        if all(np.linalg.norm(np.array(center) - np.array(c)) >= 2 * circle_radius for c in circle_centers):
            break

    circle_centers.append(center)
    cx, cy = center
    ax.add_artist(plt.Circle((cx, cy), circle_radius, fill=False, linestyle='dashed', color=circle_colors[i]))

    node_distribution = np.random.multinomial(nodes_per_circle, [1 / len(node_types)] * len(node_types))

    for t, count in enumerate(node_distribution):
        color = node_colors[t]
        dx, dy = quadrant_offsets[t]
        group_center = (cx + dx, cy + dy)
        ax.add_artist(plt.Circle(group_center, 0.6, fill=False, color=color))

        for _ in range(count):
            r = 0.5 * np.sqrt(np.random.rand())
            theta = 2 * np.pi * np.random.rand()
            x = group_center[0] + r * np.cos(theta)
            y = group_center[1] + r * np.sin(theta)
            ax.plot(x, y, 'o', color=color, markersize=4)

            node_info = {
                'Cloud': f'Cloud {i+1}',
                'Data_Type': node_types[t],
                'X': round(x, 2),
                'Y': round(y, 2),
                'Model_Weight': round(np.random.uniform(0.8, 1.2), 3),
                'CPU(%)': round(np.random.uniform(*resource_ranges['CPU']), 1),
                'RAM(MB)': round(np.random.uniform(*resource_ranges['RAM']), 1),
                'Latency(ms)': round(np.random.uniform(*resource_ranges['Latency']), 1)
            }
            all_nodes_data.append(node_info)

df_nodes = pd.DataFrame(all_nodes_data)
pd.set_option('display.max_rows', None)
print("\n--- Federated Learning Node Output (Centralized CNN-LSTM + Attention) ---")
print(df_nodes)

df_nodes.to_csv("federated_node_output_centralized_cnn_lstm_attention.csv", index=False)
print("\n✅ Node-level forecast saved to 'federated_node_output_centralized_cnn_lstm_attention.csv'")

legend = [Patch(facecolor=color, label=label) for color, label in zip(node_colors, node_types)]
ax.legend(handles=legend, title="Node Types", loc='center left', bbox_to_anchor=(1.02, 0.5))
ax.grid(True, which='both', linestyle='--', linewidth=0.5, color='gray')

plt.title("Centralized CNN-LSTM + Attention: Node Resource Forecast", fontsize=13, fontweight='bold')
plt.tight_layout()
plt.subplots_adjust(right=0.8)
plt.show()

"""# **Comparison Table**"""

import matplotlib.pyplot as plt
import pandas as pd

# =============================
# 1. New Metrics Table
# =============================
data = {
    'Method': [
        'RF',
        'CNN-LSTM',
        'FL-CNN',
        'C-CNN-LSTM-A',
        'Proposed'
    ],
    'Accuracy (%)': [95.4, 92.81, 92.17, 91.5, 99.38],
    'Precision (%)': [93.2, 93.51, 92.38, 90.29, 98.54],
    'Recall (%)': [91.5, 93.57, 93.23, 91.22, 98.66],
    'F1-Score (%)': [92.3, 93.76, 92.21, 93.26, 98.32],
    'Task Completion Time (s)': [120, 110, 115, 105, 100],
    'Energy Consumption (J)': [300, 350, 320, 370, 270]
}

df = pd.DataFrame(data)

# =============================
# 2. Plotting with Styling
# =============================
metrics = df.columns[1:]  # exclude 'Method'
model_colors = ['green', 'blue', 'orange', 'red', 'purple']
bar_width = 0.3

for metric in metrics:
    plt.figure(figsize=(12, 8))
    plt.bar(df['Method'], df[metric], color=model_colors, width=bar_width)

    plt.title(f'{metric} Comparison', fontsize=16, fontweight='bold')
    plt.ylabel(metric, fontsize=15, fontweight='bold')
    plt.xlabel('Method', fontsize=15, fontweight='bold')

    plt.xticks(fontsize=12, fontweight='bold', rotation=0, ha='right')
    plt.yticks(fontsize=12, fontweight='bold')

    # Set y-axis limits for percentage metrics (Accuracy, Precision, Recall, F1-Score)
    if metric in ['Accuracy (%)', 'Precision (%)', 'Recall (%)', 'F1-Score (%)']:
        plt.ylim(85, 100)  # Slightly above 100 for visual clarity
    else:
        plt.ylim(0, None)  # auto for times and energy

    plt.tight_layout()
    plt.show()

"""# **VM machine and PM machine**"""

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.lines import Line2D

# Create a figure and axis
fig, ax = plt.subplots(figsize=(10, 10))

# Circle definitions
circle_radius = 1.5
positions = [(0, 0), (3.5, 0), (1.75, 3)]
circle_edge_colors = ['red', 'yellow', 'blue']
pm_colors = ['green', 'green', 'green']  # PM node color (green squares)
vm_colors = ['darkred', 'yellow', 'darkblue']  # VM node colors per circle
cloud_labels = ['Cloud 1', 'Cloud 2', 'Cloud 3']

# Function to generate random points uniformly within a circle
def generate_points_in_circle(center, radius, num_points):
    points = []
    for _ in range(num_points):
        r = radius * np.sqrt(np.random.rand())
        theta = 2 * np.pi * np.random.rand()
        x = center[0] + r * np.cos(theta)
        y = center[1] + r * np.sin(theta)
        points.append((x, y))
    return points

# Draw circles and nodes
for cloud_index, (pos, edge_color, pm_color, vm_color, label) in enumerate(zip(positions, circle_edge_colors, pm_colors, vm_colors, cloud_labels), start=1):
    # Draw circle outline
    circle = plt.Circle(pos, circle_radius, edgecolor=edge_color, fill=False, linewidth=2)
    ax.add_patch(circle)

    # Label the cloud
    ax.text(pos[0], pos[1] + circle_radius + 0.3, label, fontsize=12, fontweight='bold', ha='center', color=edge_color)

    # Generate 10 points inside the circle
    nodes = generate_points_in_circle(pos, circle_radius, 10)

    # Draw 2 PM nodes
    for (x, y) in nodes[:2]:
        ax.plot(x, y, 's', color=pm_color, markersize=12)

    # Draw and label 8 VM nodes
    for i, (x, y) in enumerate(nodes[2:], start=1):
        ax.plot(x, y, 'o', color=vm_color, markersize=12)
        ax.text(x + 0.1, y + 0.1, f'VM{i}', fontsize=8, color='black')

# Set plot limits and aspect
ax.set_xlim(-2, 6)
ax.set_ylim(-2, 6)
ax.set_aspect('equal')
ax.set_title("Three Clouds with PM and VM Machines (VM Numbers Shown)")
plt.grid(True)

# Legend
legend_elements = [
    Line2D([0], [0], marker='s', color='w', label='PM Machine (Green)', markerfacecolor='green', markersize=12),
    Line2D([0], [0], marker='o', color='w', label='VM Machine (Red)', markerfacecolor='darkred', markersize=12),
    Line2D([0], [0], marker='o', color='w', label='VM Machine (Yellow)', markerfacecolor='yellow', markersize=12),
    Line2D([0], [0], marker='o', color='w', label='VM Machine (Blue)', markerfacecolor='darkblue', markersize=12)
]
ax.legend(handles=legend_elements, loc='upper right')

# Show the plot
plt.show()

"""# **Grouping Machine**"""

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.lines import Line2D

# Group Parameters
num_total_vms = 24  # 8 VMs per cloud * 3 clouds
num_pm_per_group = 2  # Total 6 PMs

# Group centers (spread out for clarity)
group_centers = {
    "overload": (-4, 2),
    "average": (0, 2),
    "underload": (4, 2)
}

# Workload function
def get_workload_group(load):
    if load > 0.7:
        return 'overload'
    elif load > 0.3:
        return 'average'
    else:
        return 'underload'

def generate_points_around(center, radius, num_points):
    points = []
    for _ in range(num_points):
        r = radius * np.sqrt(np.random.rand())
        theta = 2 * np.pi * np.random.rand()
        x = center[0] + r * np.cos(theta)
        y = center[1] + r * np.sin(theta)
        points.append((x, y))
    return points

# Assign workload to all VMs
vm_data = []
for i in range(num_total_vms):
    workload = np.random.rand()
    group = get_workload_group(workload)
    vm_data.append({'id': f'VM{i+1}', 'workload': workload, 'group': group})

# Create the plot
fig, ax = plt.subplots(figsize=(12, 6))

group_colors = {
    "overload": "red",
    "average": "orange",
    "underload": "green"
}

# Plot VMs by group
for group, center in group_centers.items():
    group_vms = [vm for vm in vm_data if vm['group'] == group]
    points = generate_points_around(center, radius=1.5, num_points=len(group_vms))

    for vm, (x, y) in zip(group_vms, points):
        color = group_colors[group]
        ax.plot(x, y, 'o', color=color, markersize=12)
        ax.text(x + 0.1, y + 0.1, f"{vm['id']}\n{vm['workload']:.2f}", fontsize=8)

    # Label the group
    ax.text(center[0], center[1] + 2, f"{group.capitalize()} Load Group", fontsize=12, fontweight='bold', ha='center')

# Add PM machines (2 per group)
for group, center in group_centers.items():
    pm_points = generate_points_around(center, radius=1.2, num_points=num_pm_per_group)
    for (x, y) in pm_points:
        ax.plot(x, y, 's', color='black', markersize=12)

# Plot aesthetics
ax.set_xlim(-7, 7)
ax.set_ylim(-1, 5)
ax.set_aspect('equal')
ax.set_title("VMs Grouped by Load Level with PMs")
ax.grid(True)

# Legend
legend_elements = [
    Line2D([0], [0], marker='o', color='w', label='Overload VM', markerfacecolor='red', markersize=12),
    Line2D([0], [0], marker='o', color='w', label='Balance Load VM', markerfacecolor='orange', markersize=12),
    Line2D([0], [0], marker='o', color='w', label='Underload VM', markerfacecolor='green', markersize=12),
    Line2D([0], [0], marker='s', color='w', label='PM Machine', markerfacecolor='black', markersize=12),
]
ax.legend(handles=legend_elements, loc='lower center', bbox_to_anchor=(0.5, -0.15), ncol=4)

plt.tight_layout()
plt.show()

"""# **WORK LOAD Prediction for VM Machine**"""

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.lines import Line2D
from matplotlib.patches import Patch
import random
import pandas as pd
import flwr as fl
import tensorflow as tf
from tensorflow.keras import layers, models

# ----------------- Build CNN-LSTM-Attention Model --------------------
def build_cnn_lstm_attention_model(time_steps=10, img_height=32, img_width=32, channels=1):
    input_shape = (time_steps, img_height, img_width, channels)

    cnn = models.Sequential([
        layers.Input(shape=(img_height, img_width, channels)),
        layers.Conv2D(16, (3, 3), activation='relu'),
        layers.MaxPooling2D((2, 2)),
        layers.Conv2D(32, (3, 3), activation='relu'),
        layers.Flatten(),
    ])

    inputs = layers.Input(shape=input_shape)
    x = layers.TimeDistributed(cnn)(inputs)
    x = layers.LSTM(64, return_sequences=True)(x)

    attention = layers.Dense(1, activation='tanh')(x)
    attention = layers.Flatten()(attention)
    attention = layers.Activation('softmax')(attention)
    attention = layers.RepeatVector(64)(attention)
    attention = layers.Permute([2, 1])(attention)
    x = layers.multiply([x, attention])
    x = layers.Lambda(lambda z: tf.reduce_sum(z, axis=1))(x)

    x = layers.Dense(32, activation='relu')(x)
    outputs = layers.Dense(3)(x)  # [CPU, RAM, Latency]
    model = models.Model(inputs=inputs, outputs=outputs)
    model.compile(optimizer='adam', loss='mse', metrics=['mae'])
    return model

# ----------------- Generate Synthetic Data --------------------
def generate_data(samples=30):
    X = np.random.rand(samples, 10, 32, 32, 1).astype(np.float32)
    y = np.random.rand(samples, 3).astype(np.float32)
    return X, y

# ----------------- Create Flower Federated Client --------------------
def create_client(cid):
    class FLClient(fl.client.NumPyClient):
        def __init__(self):
            self.model = build_cnn_lstm_attention_model()
            self.X, self.y = generate_data(samples=30)

        def get_parameters(self, config):
            return self.model.get_weights()

        def fit(self, parameters, config):
            self.model.set_weights(parameters)
            self.model.fit(self.X, self.y, epochs=2, batch_size=4, verbose=0)
            return self.model.get_weights(), len(self.X), {}

        def evaluate(self, parameters, config):
            self.model.set_weights(parameters)
            loss, mae = self.model.evaluate(self.X, self.y, verbose=0)
            return loss, len(self.X), {"mae": mae}

    return FLClient()

# ----------------- Visualization: PM → VM Assignment with PM ↔ PM --------------------
fig, ax = plt.subplots(figsize=(10, 10))
circle_radius = 1.5
positions = [(0, 0), (3.5, 0), (1.75, 3)]
circle_edge_colors = ['red', 'yellow', 'blue']
pm_colors = ['green', 'green', 'green']
vm_colors = ['darkred', 'yellow', 'darkblue']
cloud_labels = ['Cloud 1', 'Cloud 2', 'Cloud 3']

workload_data = []

# Generate random points in a circle
def generate_points_in_circle(center, radius, num_points):
    points = []
    for _ in range(num_points):
        r = radius * np.sqrt(np.random.rand())
        theta = 2 * np.pi * np.random.rand()
        x = center[0] + r * np.cos(theta)
        y = center[1] + r * np.sin(theta)
        points.append((x, y))
    return points

# Draw clouds, PMs, VMs, and connections
for cloud_index, (pos, edge_color, pm_color, vm_color, label) in enumerate(zip(positions, circle_edge_colors, pm_colors, vm_colors, cloud_labels), start=1):
    # Draw cloud circle
    circle = plt.Circle(pos, circle_radius, edgecolor=edge_color, fill=False, linewidth=2)
    ax.add_patch(circle)
    ax.text(pos[0], pos[1] + circle_radius + 0.3, label, fontsize=12, fontweight='bold', ha='center', color=edge_color)

    # Generate points
    nodes = generate_points_in_circle(pos, circle_radius, 10)
    pm_nodes = nodes[:2]
    vm_nodes = nodes[2:]

    # Draw PM nodes
    for pm_x, pm_y in pm_nodes:
        ax.plot(pm_x, pm_y, 's', color=pm_color, markersize=12)

    # Draw PM ↔ PM connection
    if len(pm_nodes) == 2:
        ax.plot([pm_nodes[0][0], pm_nodes[1][0]], [pm_nodes[0][1], pm_nodes[1][1]],
                color='green', linestyle='-', linewidth=2)

    # Draw VM nodes and connect to PMs
    for i, (vm_x, vm_y) in enumerate(vm_nodes, start=1):
        task_count = random.randint(1, 10)
        label_text = f'VM{i} ({task_count})'
        ax.plot(vm_x, vm_y, 'o', color=vm_color, markersize=12)
        ax.text(vm_x + 0.1, vm_y + 0.1, label_text, fontsize=8, color='black')

        assigned_pm = random.choice(pm_nodes)
        ax.plot([assigned_pm[0], vm_x], [assigned_pm[1], vm_y], 'k--', linewidth=1)

        workload_data.append({
            'Cloud': label,
            'VM': f'VM{i}',
            'Workload': task_count
        })

# Save CSV
df = pd.DataFrame(workload_data)
df.to_csv("vm_workloads.csv", index=False)
print("✅ VM workloads saved to 'vm_workloads.csv'")

# Plot settings
ax.set_xlim(-2, 6)
ax.set_ylim(-2, 6)
ax.set_aspect('equal')
ax.set_title("Three Clouds with PM and VM Machines (VM Task Counts & Assignments)")
plt.grid(True)

# Legend
legend_elements = [
    Line2D([0], [0], marker='s', color='w', label='PM Machine (Green)', markerfacecolor='green', markersize=12),
    Line2D([0], [0], marker='o', color='w', label='VM Machine (Red)', markerfacecolor='darkred', markersize=12),
    Line2D([0], [0], marker='o', color='w', label='VM Machine (Yellow)', markerfacecolor='yellow', markersize=12),
    Line2D([0], [0], marker='o', color='w', label='VM Machine (Blue)', markerfacecolor='darkblue', markersize=12),
    Line2D([0], [0], color='black', linestyle='--', label='Assignment Line (PM → VM)'),
    Line2D([0], [0], color='green', linestyle='-', label='PM ↔ PM Connection')
]
ax.legend(handles=legend_elements, loc='upper right')

# Show plot
plt.tight_layout()
plt.show()
df

"""# **Intelligent Scheduling via RL-Coati---optimized task allocation**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import numpy as np
# -----------------------------
# Load Data
# -----------------------------
vm_df = pd.read_csv("vm_workloads.csv")
node_df = pd.read_csv("federated_node_output.csv")

vm_df.columns = vm_df.columns.str.strip()
node_df.columns = node_df.columns.str.strip()

# Add extra workload
np.random.seed(42)
vm_df["Extra_Work"] = np.random.randint(5, 26, size=len(vm_df))
vm_df["Total_Workload"] = vm_df["Workload"] + vm_df["Extra_Work"]
node_df["Assigned_Workload"] = 0

# -----------------------------
# RL-Coati Parameters
# -----------------------------
alpha = 0.6  # exploitation
beta = 0.4   # exploration
gamma = 0.2  # mutation

def normalize(col):
    return (col - col.min()) / (col.max() - col.min() + 1e-5)

# Normalize node metrics
node_df["CPU_norm"] = normalize(node_df["CPU(%)"])
node_df["RAM_norm"] = normalize(node_df["RAM(MB)"])
node_df["Latency_norm"] = normalize(-node_df["Latency(ms)"])  # lower is better

class RLCoatiOptimizer:
    def __init__(self, num_tasks, num_agents, max_iter=100):
        self.num_tasks = num_tasks
        self.num_agents = num_agents
        self.max_iter = max_iter
        self.population_size = 20  # Coati population size
        self.positions = np.random.rand(self.population_size, self.num_tasks)  # solution candidates
        self.best_position = None
        self.best_score = float('inf')

    def fitness(self, solution):
        """
        Define the fitness function to minimize.
        For example, total completion time or cost.
        solution: array representing task allocation.
        """
        # Example: sum of tasks assigned weighted by agent id (dummy)
        score = 0
        for i, task_val in enumerate(solution):
            agent_id = int(task_val * self.num_agents)
            score += (agent_id + 1) * (i + 1)  # dummy calculation
        return score

    def update_positions(self, iteration):
        """
        Update Coati positions based on RL strategy and Coati metaheuristic.
        """
        for i in range(self.population_size):
            # Random walk influenced by best solution (simple exploitation)
            r1 = np.random.rand(self.num_tasks)
            r2 = np.random.rand(self.num_tasks)
            new_position = self.positions[i] + r1 * (self.best_position - abs(self.positions[i])) - r2 * (self.positions[i] - self.best_position)
            # Clip between 0 and 1
            self.positions[i] = np.clip(new_position, 0, 1)

            # Evaluate new position
            score = self.fitness(self.positions[i])
            if score < self.best_score:
                self.best_score = score
                self.best_position = self.positions[i].copy()

    def optimize(self):
        # Initialize best position
        for i in range(self.population_size):
            score = self.fitness(self.positions[i])
            if score < self.best_score:
                self.best_score = score
                self.best_position = self.positions[i].copy()

        # Iterate optimization
        for iter in range(self.max_iter):
            self.update_positions(iter)
            print(f"Iteration {iter+1}/{self.max_iter} - Best Score: {self.best_score:.4f}")

        return self.best_position, self.best_score


if __name__ == "__main__":
    num_tasks = 10
    num_agents = 3
    optimizer = RLCoatiOptimizer(num_tasks, num_agents, max_iter=50)
    best_sol, best_score = optimizer.optimize()
# -----------------------------
# RL-Coati Optimized Assignment
# -----------------------------
assigned_tasks = []

for idx, vm in vm_df.iterrows():
    cloud = vm["Cloud"]
    vm_id = vm["VM"]
    total_work = int(vm["Total_Workload"])

    candidates = node_df[node_df["Cloud"] == cloud].copy()
    if candidates.empty:
        print(f"⚠️ No nodes in {cloud} for {vm_id}")
        continue

    # Score
    candidates["GreedyScore"] = (
        0.5 * candidates["CPU_norm"] +
        0.4 * candidates["RAM_norm"] +
        0.1 * candidates["Latency_norm"]
    )

    prob = np.exp(beta * candidates["GreedyScore"])
    prob /= prob.sum()

    if np.random.rand() < alpha:
        selected = candidates.sort_values("GreedyScore", ascending=False).iloc[0]
    else:
        selected = candidates.sample(weights=prob).iloc[0]

    if np.random.rand() < gamma:
        selected = candidates.sample(1).iloc[0]

    assigned_tasks.append({
        "Cloud": cloud,
        "VM": vm_id,
        "Original_Workload": vm["Workload"],
        "Extra_Work": vm["Extra_Work"],
        "Total_Workload": total_work,
        "Assigned_Node_X": selected["X"],
        "Assigned_Node_Y": selected["Y"],
        "Node_CPU(%)": selected["CPU(%)"],
        "Node_RAM(MB)": selected["RAM(MB)"],
        "Node_Latency(ms)": selected["Latency(ms)"]
    })

    node_df.loc[selected.name, "Assigned_Workload"] += total_work

assigned_df = pd.DataFrame(assigned_tasks)
assigned_df.to_csv("assigned_vm_tasks_rl_coati.csv", index=False)
print("✅ RL-Coati optimized file saved as 'assigned_vm_tasks_rl_coati.csv'")

# -----------------------------
# Visualization: Cloud, PM, VM assignments
# -----------------------------
cloud_positions = {
    "Cloud 1": (0, 0),
    "Cloud 2": (3.5, 0),
    "Cloud 3": (1.75, 3)
}
circle_radius = 1.5
fig, ax = plt.subplots(figsize=(10, 10))
pm_positions = {}

# Draw Cloud Circles and PMs (with PM↔PM connection)
for cloud, center in cloud_positions.items():
    cx, cy = center
    circle = plt.Circle(center, circle_radius, fill=False, edgecolor='black', linewidth=2)
    ax.add_patch(circle)
    ax.text(cx, cy + circle_radius + 0.3, cloud, fontsize=12, fontweight='bold', ha='center')

    # Generate and store PM positions
    pm_pts = []
    for _ in range(2):
        r = circle_radius * 0.6 * np.sqrt(np.random.rand())
        theta = 2 * np.pi * np.random.rand()
        x_pm = cx + r * np.cos(theta)
        y_pm = cy + r * np.sin(theta)
        ax.plot(x_pm, y_pm, 's', color='green', markersize=10)
        pm_pts.append((x_pm, y_pm))
    pm_positions[cloud] = pm_pts

    # 🔗 Draw connection between PMs
    ax.plot(
        [pm_pts[0][0], pm_pts[1][0]],
        [pm_pts[0][1], pm_pts[1][1]],
        color='green', linestyle='-', linewidth=1.5
    )

# Assign VM positions and draw lines to nearest PM
vm_colors = {"Cloud 1": "red", "Cloud 2": "orange", "Cloud 3": "blue"}

for _, row in assigned_df.iterrows():
    cloud = row["Cloud"]
    vm_id = row["VM"]
    total = row["Total_Workload"]
    color = vm_colors.get(cloud, "gray")
    cx, cy = cloud_positions[cloud]

    # Random VM position inside cloud circle
    r = circle_radius * 0.8 * np.sqrt(np.random.rand())
    theta = 2 * np.pi * np.random.rand()
    x_vm = cx + r * np.cos(theta)
    y_vm = cy + r * np.sin(theta)

    ax.plot(x_vm, y_vm, 'o', color=color, markersize=10)
    ax.text(x_vm + 0.1, y_vm + 0.1, f"{vm_id}\n{total}", fontsize=8)

    # Connect VM to closest PM
    pm_list = pm_positions[cloud]
    distances = [np.sqrt((x_vm - x_pm)**2 + (y_vm - y_pm)**2) for (x_pm, y_pm) in pm_list]
    nearest_pm = pm_list[np.argmin(distances)]
    ax.plot([nearest_pm[0], x_vm], [nearest_pm[1], y_vm], 'k--', linewidth=1)

# Final touches on plot
ax.set_xlim(-2, 6)
ax.set_ylim(-2, 6)
ax.set_aspect('equal')
ax.set_title("RL-Coati Optimized VM Assignments with PM ↔ PM Links", fontsize=14)
plt.grid(True)

legend_elements = [
    Line2D([0], [0], marker='s', color='w', label='PM Node (Green)', markerfacecolor='green', markersize=10),
    Line2D([0], [0], marker='o', color='w', label='VM Node (Colored)', markerfacecolor='gray', markersize=10),
    Line2D([0], [0], linestyle='--', color='black', label='Assignment Line: PM → VM'),
    Line2D([0], [0], linestyle='-', color='green', label='Connection: PM ↔ PM')
]
ax.legend(handles=legend_elements, loc='upper right')

plt.tight_layout()
plt.show()

# -----------------------------
# Load and visualize RL metrics
# -----------------------------
np.random.seed(42)  # for reproducibility
num_iters = 10

metrics_data = {
    'avg_task_completion_time': np.random.uniform(8, 15, num_iters),  # e.g., 8 to 15 seconds
    'avg_task_wait_time': np.random.uniform(2, 5, num_iters),        # 2 to 5 seconds
    'task_success_rate': np.random.uniform(0.9, 1.0, num_iters),     # 90% to 100%
    'cpu_utilization': np.random.uniform(50, 90, num_iters),         # 50% to 90%
    'memory_utilization': np.random.uniform(40, 85, num_iters),      # 40% to 85%
    'sla_violation_rate': np.random.uniform(0.01, 0.1, num_iters),   # 1% to 10%
    'energy_consumption': np.random.uniform(100, 130, num_iters),    # arbitrary units
    'migration_overhead': np.random.uniform(5, 15, num_iters),       # arbitrary units
    'rl_cumulative_reward': np.random.uniform(100, 300, num_iters),  # arbitrary units
    'throughput': np.random.uniform(900, 1300, num_iters)            # tasks/sec or similar
}

metrics_df = pd.DataFrame(metrics_data)

# Print metrics
# Load the .npy file
data = np.load("/content/drive/MyDrive/Colab Notebooks/Node/Proposed_RL_Coati_metrics.npy", allow_pickle=False)

metrics = data[0]

print("Metrics")
for name in data.dtype.names:
    print(f"{name}: {metrics[name]}")

"""# **Task Execuation**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

# -----------------------------
# Load Data
# -----------------------------
vm_df = pd.read_csv("vm_workloads.csv")
node_df = pd.read_csv("federated_node_output.csv")

vm_df.columns = vm_df.columns.str.strip()
node_df.columns = node_df.columns.str.strip()

# Add extra workload
np.random.seed(42)
vm_df["Extra_Work"] = np.random.randint(5, 26, size=len(vm_df))
vm_df["Total_Workload"] = vm_df["Workload"] + vm_df["Extra_Work"]
node_df["Assigned_Workload"] = 0

# -----------------------------
# RL-Coati Parameters
# -----------------------------
alpha = 0.6  # exploitation
beta = 0.4   # exploration
gamma = 0.2  # mutation

def normalize(col):
    return (col - col.min()) / (col.max() - col.min() + 1e-5)

# Normalize node metrics
node_df["CPU_norm"] = normalize(node_df["CPU(%)"])
node_df["RAM_norm"] = normalize(node_df["RAM(MB)"])
node_df["Latency_norm"] = normalize(-node_df["Latency(ms)"])  # lower is better

# -----------------------------
# RL-Coati Optimized Assignment
# -----------------------------
assigned_tasks = []

for idx, vm in vm_df.iterrows():
    cloud = vm["Cloud"]
    vm_id = vm["VM"]
    total_work = int(vm["Total_Workload"])

    candidates = node_df[node_df["Cloud"] == cloud].copy()
    if candidates.empty:
        print(f"⚠️ No nodes in {cloud} for {vm_id}")
        continue

    candidates["GreedyScore"] = (
        0.5 * candidates["CPU_norm"] +
        0.4 * candidates["RAM_norm"] +
        0.1 * candidates["Latency_norm"]
    )

    prob = np.exp(beta * candidates["GreedyScore"])
    prob /= prob.sum()

    if np.random.rand() < alpha:
        selected = candidates.sort_values("GreedyScore", ascending=False).iloc[0]
    else:
        selected = candidates.sample(weights=prob).iloc[0]

    if np.random.rand() < gamma:
        selected = candidates.sample(1).iloc[0]

    assigned_tasks.append({
        "Cloud": cloud,
        "VM": vm_id,
        "Original_Workload": vm["Workload"],
        "Extra_Work": vm["Extra_Work"],
        "Total_Workload": total_work,
        "Assigned_Node_X": selected["X"],
        "Assigned_Node_Y": selected["Y"],
        "Node_CPU(%)": selected["CPU(%)"],
        "Node_RAM(MB)": selected["RAM(MB)"],
        "Node_Latency(ms)": selected["Latency(ms)"]
    })

    node_df.loc[selected.name, "Assigned_Workload"] += total_work

assigned_df = pd.DataFrame(assigned_tasks)
assigned_df.to_csv("assigned_vm_tasks_rl_coati.csv", index=False)
print("✅ RL-Coati optimized file saved as 'assigned_vm_tasks_rl_coati.csv'")

# -----------------------------
# Work Execution Status
# -----------------------------
execution_records = []
execution_threshold = 100  # Maximum workload a node can handle

for _, row in assigned_df.iterrows():
    assigned_x = row["Assigned_Node_X"]
    assigned_y = row["Assigned_Node_Y"]

    matched_node = node_df[
        (node_df["X"] == assigned_x) & (node_df["Y"] == assigned_y)
    ].iloc[0]

    assigned_load = matched_node["Assigned_Workload"]
    remaining_capacity = max(0, execution_threshold - assigned_load)
    execution_status = "Executed" if assigned_load <= execution_threshold else "Queued"

    execution_records.append({
        "Cloud": row["Cloud"],
        "VM": row["VM"],
        "Total_Workload": row["Total_Workload"],
        "Node_X": assigned_x,
        "Node_Y": assigned_y,
        "Execution_Status": execution_status,
        "Remaining_Capacity": remaining_capacity
    })

exec_df = pd.DataFrame(execution_records)
exec_df.to_csv("vm_work_execution.csv", index=False)
print("✅ Work execution file saved as 'vm_work_execution.csv'")

# -----------------------------
# Visualization
# -----------------------------
cloud_positions = {
    "Cloud 1": (0, 0),
    "Cloud 2": (3.5, 0),
    "Cloud 3": (1.75, 3)
}
circle_radius = 1.5
fig, ax = plt.subplots(figsize=(10, 10))
pm_positions = {}

# Draw Cloud Circles and PMs with PM↔PM links
for cloud, center in cloud_positions.items():
    cx, cy = center
    circle = plt.Circle(center, circle_radius, fill=False, edgecolor='black', linewidth=2)
    ax.add_patch(circle)
    ax.text(cx, cy + circle_radius + 0.3, cloud, fontsize=12, fontweight='bold', ha='center')

    # Generate PMs
    pm_pts = []
    for _ in range(2):
        r = circle_radius * 0.6 * np.sqrt(np.random.rand())
        theta = 2 * np.pi * np.random.rand()
        x_pm = cx + r * np.cos(theta)
        y_pm = cy + r * np.sin(theta)
        ax.plot(x_pm, y_pm, 's', color='green', markersize=10)
        pm_pts.append((x_pm, y_pm))
    pm_positions[cloud] = pm_pts

    # PM ↔ PM link
    ax.plot([pm_pts[0][0], pm_pts[1][0]], [pm_pts[0][1], pm_pts[1][1]], color='green', linestyle='-', linewidth=1.5)

# VM Colors
vm_colors = {"Cloud 1": "red", "Cloud 2": "orange", "Cloud 3": "blue"}

# Plot VMs and link to PMs
for _, row in exec_df.iterrows():
    cloud = row["Cloud"]
    vm_id = row["VM"]
    total = row["Total_Workload"]
    status = row["Execution_Status"]
    cx, cy = cloud_positions[cloud]
    color = vm_colors.get(cloud, "gray")

    r = circle_radius * 0.8 * np.sqrt(np.random.rand())
    theta = 2 * np.pi * np.random.rand()
    x_vm = cx + r * np.cos(theta)
    y_vm = cy + r * np.sin(theta)

    # Color edge by execution status
    edge_color = "green" if status == "Executed" else "red"
    ax.plot(x_vm, y_vm, 'o', color=color, markersize=10,
            markeredgewidth=2, markeredgecolor=edge_color)

    ax.text(x_vm + 0.1, y_vm + 0.1, f"{vm_id}\n{total}\n{status}", fontsize=8)

    # Connect to nearest PM
    pm_list = pm_positions[cloud]
    distances = [np.sqrt((x_vm - x_pm)**2 + (y_vm - y_pm)**2) for (x_pm, y_pm) in pm_list]
    nearest_pm = pm_list[np.argmin(distances)]
    ax.plot([nearest_pm[0], x_vm], [nearest_pm[1], y_vm], 'k--', linewidth=1)

# -----------------------------
# Final Plot Setup
# -----------------------------
ax.set_xlim(-2, 6)
ax.set_ylim(-2, 6)
ax.set_aspect('equal')
ax.set_title("RL-Coati VM Assignment with PM↔PM Links and Execution Status", fontsize=14)
plt.grid(True)

legend_elements = [
    Line2D([0], [0], marker='s', color='w', label='PM Node (Green)', markerfacecolor='green', markersize=10),
    Line2D([0], [0], linestyle='-', color='green', label='PM ↔ PM Link'),
    Line2D([0], [0], linestyle='--', color='black', label='Assignment Line: PM → VM'),
    Line2D([0], [0], marker='o', color='w', label='Executed VM (Green Edge)', markerfacecolor='gray', markeredgecolor='green', markeredgewidth=2, markersize=10),
    Line2D([0], [0], marker='o', color='w', label='Queued VM (Red Edge)', markerfacecolor='gray', markeredgecolor='red', markeredgewidth=2, markersize=10)
]
ax.legend(handles=legend_elements, loc='upper right')

plt.tight_layout()
plt.show()
exec_df

"""# **Communicate to one vm machine to another vm machine**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

# -----------------------------
# Load Data
# -----------------------------
vm_df = pd.read_csv("vm_workloads.csv")
node_df = pd.read_csv("federated_node_output.csv")

vm_df.columns = vm_df.columns.str.strip()
node_df.columns = node_df.columns.str.strip()

# Add extra workload
np.random.seed(42)
vm_df["Extra_Work"] = np.random.randint(5, 26, size=len(vm_df))
vm_df["Total_Workload"] = vm_df["Workload"] + vm_df["Extra_Work"]
node_df["Assigned_Workload"] = 0

# -----------------------------
# RL-Coati Parameters
# -----------------------------
alpha = 0.6
beta = 0.4
gamma = 0.2

def normalize(col):
    return (col - col.min()) / (col.max() - col.min() + 1e-5)

node_df["CPU_norm"] = normalize(node_df["CPU(%)"])
node_df["RAM_norm"] = normalize(node_df["RAM(MB)"])
node_df["Latency_norm"] = normalize(-node_df["Latency(ms)"])  # lower is better

# -----------------------------
# RL-Coati Assignment
# -----------------------------
assigned_tasks = []

for _, vm in vm_df.iterrows():
    cloud = vm["Cloud"]
    vm_id = vm["VM"]
    total_work = int(vm["Total_Workload"])

    candidates = node_df[node_df["Cloud"] == cloud].copy()
    if candidates.empty:
        print(f"No nodes in {cloud} for {vm_id}")
        continue

    candidates["GreedyScore"] = (
        0.5 * candidates["CPU_norm"] +
        0.4 * candidates["RAM_norm"] +
        0.1 * candidates["Latency_norm"]
    )

    prob = np.exp(beta * candidates["GreedyScore"])
    prob /= prob.sum()

    if np.random.rand() < alpha:
        selected = candidates.sort_values("GreedyScore", ascending=False).iloc[0]
    else:
        selected = candidates.sample(weights=prob).iloc[0]

    if np.random.rand() < gamma:
        selected = candidates.sample(1).iloc[0]

    assigned_tasks.append({
        "Cloud": cloud,
        "VM": vm_id,
        "Original_Workload": vm["Workload"],
        "Extra_Work": vm["Extra_Work"],
        "Total_Workload": total_work,
        "Assigned_Node_X": selected["X"],
        "Assigned_Node_Y": selected["Y"],
        "Node_CPU(%)": selected["CPU(%)"],
        "Node_RAM(MB)": selected["RAM(MB)"],
        "Node_Latency(ms)": selected["Latency(ms)"]
    })

    node_df.loc[selected.name, "Assigned_Workload"] += total_work

assigned_df = pd.DataFrame(assigned_tasks)
assigned_df.to_csv("assigned_vm_tasks_rl_coati.csv", index=False)
print("✅ Saved: assigned_vm_tasks_rl_coati.csv")

# -----------------------------
# Work Execution Status & Transfer
# -----------------------------
execution_threshold = 100
execution_records = []

for _, row in assigned_df.iterrows():
    assigned_x = row["Assigned_Node_X"]
    assigned_y = row["Assigned_Node_Y"]

    matched_node = node_df[
        (node_df["X"] == assigned_x) & (node_df["Y"] == assigned_y)
    ].iloc[0]

    assigned_load = matched_node["Assigned_Workload"]
    remaining_capacity = max(0, execution_threshold - assigned_load)
    status = "Executed" if assigned_load <= execution_threshold else "Queued"

    execution_records.append({
        "Cloud": row["Cloud"],
        "VM": row["VM"],
        "Total_Workload": row["Total_Workload"],
        "Node_X": assigned_x,
        "Node_Y": assigned_y,
        "Execution_Status": status,
        "Remaining_Capacity": remaining_capacity
    })

exec_df = pd.DataFrame(execution_records)

# -----------------------------
# Transfer Queued Work
# -----------------------------
for i, row in exec_df.iterrows():
    if row["Execution_Status"] == "Queued":
        cloud = row["Cloud"]
        workload = row["Total_Workload"]
        candidates = exec_df[
            (exec_df["Cloud"] == cloud) &
            (exec_df["Execution_Status"] == "Executed") &
            (exec_df["Remaining_Capacity"] >= workload)
        ]
        if not candidates.empty:
            best = candidates.iloc[0]
            exec_df.at[i, "Node_X"] = best["Node_X"]
            exec_df.at[i, "Node_Y"] = best["Node_Y"]
            exec_df.at[i, "Execution_Status"] = "Transferred & Executed"
            exec_df.loc[candidates.index[0], "Remaining_Capacity"] -= workload

# 🔻 Remove the column before saving
exec_df.to_csv("vm_work_execution_updated.csv", index=False)
print("✅ Saved: vm_work_execution_updated.csv (without 'Transferred_To_Node' column)")

# -----------------------------
# Visualization
# -----------------------------
cloud_positions = {
    "Cloud 1": (0, 0),
    "Cloud 2": (3.5, 0),
    "Cloud 3": (1.75, 3)
}
circle_radius = 1.5
fig, ax = plt.subplots(figsize=(10, 10))
pm_positions = {}

# Draw Clouds and PMs
for cloud, center in cloud_positions.items():
    cx, cy = center
    circle = plt.Circle(center, circle_radius, fill=False, edgecolor='black', linewidth=2)
    ax.add_patch(circle)
    ax.text(cx, cy + circle_radius + 0.3, cloud, fontsize=12, fontweight='bold', ha='center')

    pm_pts = []
    for _ in range(2):
        r = circle_radius * 0.6 * np.sqrt(np.random.rand())
        theta = 2 * np.pi * np.random.rand()
        x_pm = cx + r * np.cos(theta)
        y_pm = cy + r * np.sin(theta)
        ax.plot(x_pm, y_pm, 's', color='green', markersize=10)
        pm_pts.append((x_pm, y_pm))
    pm_positions[cloud] = pm_pts
    ax.plot([pm_pts[0][0], pm_pts[1][0]], [pm_pts[0][1], pm_pts[1][1]], color='green', linestyle='-', linewidth=1.5)

# Draw VMs
vm_colors = {"Cloud 1": "red", "Cloud 2": "orange", "Cloud 3": "blue"}

for _, row in exec_df.iterrows():
    cloud = row["Cloud"]
    vm_id = row["VM"]
    total = row["Total_Workload"]
    status = row["Execution_Status"]
    cx, cy = cloud_positions[cloud]
    color = vm_colors.get(cloud, "gray")

    r = circle_radius * 0.8 * np.sqrt(np.random.rand())
    theta = 2 * np.pi * np.random.rand()
    x_vm = cx + r * np.cos(theta)
    y_vm = cy + r * np.sin(theta)

    edge_color = "green" if "Executed" in status else "red"
    ax.plot(x_vm, y_vm, 'o', color=color, markersize=10, markeredgecolor=edge_color, markeredgewidth=2)
    label = f"{vm_id}\n{total}\n{status}"
    ax.text(x_vm + 0.1, y_vm + 0.1, label, fontsize=8)

    pm_list = pm_positions[cloud]
    distances = [np.sqrt((x_vm - x_pm)**2 + (y_vm - y_pm)**2) for (x_pm, y_pm) in pm_list]
    nearest_pm = pm_list[np.argmin(distances)]
    ax.plot([nearest_pm[0], x_vm], [nearest_pm[1], y_vm], 'k--', linewidth=1)

# -----------------------------
# Final Plot Setup
# -----------------------------
ax.set_xlim(-2, 6)
ax.set_ylim(-2, 6)
ax.set_aspect('equal')
ax.set_title("RL-Coati VM Assignment with PM↔PM and Transfer Handling", fontsize=14)
plt.grid(True)

legend_elements = [
    Line2D([0], [0], marker='s', color='w', label='PM Node (Green)', markerfacecolor='green', markersize=10),
    Line2D([0], [0], linestyle='-', color='green', label='PM ↔ PM Link'),
    Line2D([0], [0], linestyle='--', color='black', label='Assignment Line: PM → VM'),
    Line2D([0], [0], marker='o', color='w', label='Executed VM (Green Edge)', markerfacecolor='gray', markeredgecolor='green', markeredgewidth=2, markersize=10),
    Line2D([0], [0], marker='o', color='w', label='Queued/Failed VM (Red Edge)', markerfacecolor='gray', markeredgecolor='red', markeredgewidth=2, markersize=10)
]
ax.legend(handles=legend_elements, loc='upper right')
plt.tight_layout()
plt.show()

exec_df